version: '3.5'

services:
  web:
    image: gatherone_ai
    container_name: gatherone_ai_web_server
    command: uvicorn main:app --host 0.0.0.0 --port 11112
    volumes:
      - /var/log/ai/web:/home/logs:rw
    network_mode: host
